steps:
  - label: "example master"
    command: .buildkite/scripts/example.sh
    plugins:
      - docker#v3.8.0:
          image: "baguasys/bagua:latest"
          propagate-environment: true
          propagate-uid-gid: true
          runtime: nvidia
          network: host
          always-pull: true
    agents:
      queue: "master"
  - label: "benchmark"
    parallelism: 1
    command: bash .buildkite/scripts/benchmark.sh
    plugins:
      - docker#v3.8.0:
          image: "baguasys/bagua:latest"
          propagate-uid-gid: true
          propagate-environment: true
          runtime: nvidia
          network: host
          environment:
            - "PATH=/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            - "LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs/:/usr/local/lib64:/usr/local/lib"
          ipc: host
          shm-size: 100gb
          always-pull: true
