# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: baguasys/bagua:master-pytorch-1.9.0-cuda11.1-cudnn8
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: rustup default stable
    - name: Install with pip
      run: |
        python -m pip install --pre .
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-timeout
    - name: Test with pytest
      run: |
        rm -rf bagua bagua_core
        pytest -s --timeout=300 --timeout_method=thread
  build-ten:
    runs-on: ubuntu-latest
    container: baguasys/bagua:master-pytorch-1.10.0-cuda11.3-cudnn8
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: rustup default stable
    - name: Install with pip
      run: |
        python -m pip install --pre .
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-timeout
    - name: Test with pytest
      run: |
        rm -rf bagua bagua_core
        pytest -s --timeout=300 --timeout_method=thread
  build-eleven:
    runs-on: ubuntu-latest
    container: baguasys/bagua:master-pytorch-1.11.0-cuda11.3-cudnn8
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: rustup default stable
    - name: Install with pip
      run: |
        python -m pip install --pre .
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-timeout
    - name: Test with pytest
      run: |
        rm -rf bagua bagua_core
        pytest -s --timeout=300 --timeout_method=thread
  build-twelve:
    runs-on: ubuntu-latest
    container: baguasys/bagua:master-pytorch-1.12.0-cuda11.3-cudnn8
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: rustup default stable
    - name: Install with pip
      run: |
        python -m pip install --pre .
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-timeout
    - name: Test with pytest
      run: |
        rm -rf bagua bagua_core
        pytest -s --timeout=300 --timeout_method=thread
  build-thirteen:
    runs-on: ubuntu-latest
    container: baguasys/bagua:master-pytorch-1.13.0-cuda11.6-cudnn8
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: rustup default stable
    - name: Install with pip
      run: |
        python -m pip install --pre .
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-timeout
    - name: Test with pytest
      run: |
        rm -rf bagua bagua_core
        pytest -s --timeout=300 --timeout_method=thread
  build-twenty:
    runs-on: ubuntu-latest
    container: baguasys/bagua:master-pytorch-2.0.0-cuda11.7-cudnn8
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: rustup default stable
    - name: Install with pip
      run: |
        python -m pip install --pre .
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-timeout
    - name: Test with pytest
      run: |
        rm -rf bagua bagua_core
        pytest -s --timeout=300 --timeout_method=thread
